name: test
on: push
jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
     - name: hello
       run: echo "good morning"
    
  job2:
   runs-on: ubuntu-latest
   steps:
    - name: byeee
      run: echo "good night"